<?php
// Add a few resources auto generated by stations manually
$unsorted['Name'][] = $items['18002']['Name']; $unsorted['ResourceID'][] = '18002'; // Honey
$unsorted['Name'][] = $items['18010']['Name']; $unsorted['ResourceID'][] = '18010';	// Unappetizing Fish
$unsorted['Name'][] = $items['18011']['Name']; $unsorted['ResourceID'][] = '18011';	// Savory Fish
$unsorted['Name'][] = $items['18012']['Name']; $unsorted['ResourceID'][] = '18012';	// Exotic Fish
$unsorted['Name'][] = $items['18020']['Name']; $unsorted['ResourceID'][] = '18020';	// Unappetizing Shellfish
$unsorted['Name'][] = $items['18021']['Name']; $unsorted['ResourceID'][] = '18021';	// Savory Shellfish
$unsorted['Name'][] = $items['18022']['Name']; $unsorted['ResourceID'][] = '18022';	// Exotic Shellfish
// Add a few more resources that are missing for some reason
$unsorted['Name'][] = $items['100']['Name']; $unsorted['ResourceID'][] = '100';		// Water (helper resource)
$unsorted['Name'][] = $items['11112']['Name']; $unsorted['ResourceID'][] = '11112';	// xx_beastblood
$unsorted['Name'][] = $items['11128']['Name']; $unsorted['ResourceID'][] = '11128';	// True Indigo Seeds
$unsorted['Name'][] = $items['13002']['Name']; $unsorted['ResourceID'][] = '13002';	// Savory Flesh
$unsorted['Name'][] = $items['13003']['Name']; $unsorted['ResourceID'][] = '13003';	// Exotic Flesh
$unsorted['Name'][] = $items['13052']['Name']; $unsorted['ResourceID'][] = '13052';	// Eyes of Innocence
$unsorted['Name'][] = $items['13598']['Name']; $unsorted['ResourceID'][] = '13598';	// Rotten Devil's Bonemeal
$unsorted['Name'][] = $items['15501']['Name']; $unsorted['ResourceID'][] = '15501';	// Heart of a Hero
$unsorted['Name'][] = $items['15502']['Name']; $unsorted['ResourceID'][] = '15502';	// Ancient Rhino Horn
$unsorted['Name'][] = $items['82047']['Name']; $unsorted['ResourceID'][] = '82047';	// Jungle Bird Head
$unsorted['Name'][] = $items['82050']['Name']; $unsorted['ResourceID'][] = '82050';	// Jaguar Head
$unsorted['Name'][] = $items['82072']['Name']; $unsorted['ResourceID'][] = '82072';	// Jungle Bird Head
$unsorted['Name'][] = $items['82073']['Name']; $unsorted['ResourceID'][] = '82073';	// Jungle Bird Head
// Remove some that shouldn't be considered resources
$keys = array_keys($unsorted['ResourceID'], '18263'); foreach($keys as $key) { unset($unsorted['ResourceID'][$key]); unset($unsorted['Name'][$key]); }	// Salt
$keys = array_keys($unsorted['ResourceID'], '80532'); foreach($keys as $key) { unset($unsorted['ResourceID'][$key]); unset($unsorted['Name'][$key]); }	// Witchfire Powder
$keys = array_keys($unsorted['ResourceID'], '80661'); foreach($keys as $key) { unset($unsorted['ResourceID'][$key]); unset($unsorted['Name'][$key]); }	// Iron Pot
$keys = array_keys($unsorted['ResourceID'], '80662'); foreach($keys as $key) { unset($unsorted['ResourceID'][$key]); unset($unsorted['Name'][$key]);  }	// Mortarium
$keys = array_keys($unsorted['ResourceID'], '80663'); foreach($keys as $key) { unset($unsorted['ResourceID'][$key]); unset($unsorted['Name'][$key]); }	// Iron Pan
?>